api_base_url: https://api.bifrost.saastack.site
project_id: 770468e8-9fee-446c-aa8f-05df3af6cec7
project_name: 770468e8-9fee-446c-aa8f-05df3af6cec7
service_id: cff91d9d-b35a-458a-9c9b-7eb5380358e3
service_name: web
environment_id: 899f4ee1-2a2c-44a5-ba43-699722dee18e
environment_name: dev
repository_url: https://github.com/spandan-kumar/vantage.git
default_branch: main
dockerfile_path: Dockerfile
docker_context: .
